# Generated by Django 5.2.4 on 2025-07-21 18:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=220, unique=True)),
                ('content', models.TextField()),
                ('summary', models.CharField(blank=True, max_length=300)),
                ('published_at', models.DateTimeField()),
                ('author', models.CharField(max_length=100)),
                ('reactions', models.JSONField(blank=True, default=dict)),
                ('comments_enabled', models.BooleanField(default=True)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='blog/')),
                ('categories', models.ManyToManyField(blank=True, to='projects.category')),
                ('tags', models.ManyToManyField(blank=True, to='projects.tag')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(max_length=100)),
                ('author_email', models.EmailField(max_length=254)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reactions', models.JSONField(blank=True, default=dict)),
                ('blogpost', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='blog.blogpost')),
            ],
        ),
    ]
